# Generated by Django 2.2.9 on 2020-04-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farming_location', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('join_date', models.DateField()),
                ('stop_date', models.DateField(null=True)),
                ('locality', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
