# Generated by Django 2.2.9 on 2020-04-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager_details',
            name='designation',
        ),
    ]
