# Generated by Django 2.2.9 on 2020-04-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('designation', models.CharField(max_length=15)),
                ('locality', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('advance', models.IntegerField()),
                ('worked_days', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
