# Generated by Django 2.2.9 on 2020-04-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_employee_salary_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_salary_transactions',
            name='advance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
